#!/usr/bin/env bash
# Render the Homebrew formula for a given release into
# <outdir>/Formula/mq-bridge-meilisearch.rb, taking each archive's sha256 from the
# .sha256 sidecar the release publishes beside it. It does not push anything:
# the caller copies the output into marcomq/homebrew-tap.
#
# Usage:
#   render.sh <tag> [repo] [outdir]
#     tag       release tag, e.g. 0.1.1   (required)
#     repo      owner/name  (default: marcomq/mq-bridge-meilisearch)
#     outdir    where to write Formula/ (default: ./out)
set -euo pipefail

TAG="${1:?usage: render.sh <tag> [repo] [outdir]}"
REPO="${2:-marcomq/mq-bridge-meilisearch}"
OUTDIR="${3:-out}"
VERSION="${TAG#v}"
BASE="https://github.com/${REPO}/releases/download/${TAG}"

sha() {
  local sum
  sum="$(curl -fsSL "${BASE}/mq-bridge-meilisearch-${VERSION}-$1.tar.gz.sha256" | cut -d' ' -f1)"
  [[ "$sum" =~ ^[0-9a-f]{64}$ ]] || { echo "bad checksum for $1: '$sum'" >&2; exit 1; }
  echo "$sum"
}

echo "resolving checksums for ${REPO} ${TAG} ..." >&2
MAC_ARM="$(sha aarch64-apple-darwin)"
MAC_X64="$(sha x86_64-apple-darwin)"
LINUX_X64="$(sha x86_64-unknown-linux-gnu)"
LINUX_ARM64="$(sha aarch64-unknown-linux-gnu)"

mkdir -p "${OUTDIR}/Formula"

cat > "${OUTDIR}/Formula/mq-bridge-meilisearch.rb" <<RUBY
# typed: false
# frozen_string_literal: true
# Generated by packaging/homebrew/render.sh in marcomq/mq-bridge-meilisearch — do not edit by hand.
class MqBridgeMeilisearch < Formula
  desc "Meilisearch endpoint plugin for mq-bridge"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "${BASE}/mq-bridge-meilisearch-${VERSION}-aarch64-apple-darwin.tar.gz"
      sha256 "${MAC_ARM}"
    end
    on_intel do
      url "${BASE}/mq-bridge-meilisearch-${VERSION}-x86_64-apple-darwin.tar.gz"
      sha256 "${MAC_X64}"
    end
  end

  on_linux do
    on_intel do
      url "${BASE}/mq-bridge-meilisearch-${VERSION}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${LINUX_X64}"
    end
    on_arm do
      url "${BASE}/mq-bridge-meilisearch-${VERSION}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${LINUX_ARM64}"
    end
  end

  def install
    # \$HOMEBREW_PREFIX/lib/mq-bridge is on mq-bridge's plugin search path.
    (lib/"mq-bridge").install Dir["libmq_bridge_meilisearch.*"]
    doc.install "LICENSE-MIT", "LICENSE-APACHE"
  end

  test do
    ext = OS.mac? ? "dylib" : "so"
    assert_predicate lib/"mq-bridge/libmq_bridge_meilisearch.#{ext}", :exist?
  end
end
RUBY

echo "wrote ${OUTDIR}/Formula/mq-bridge-meilisearch.rb" >&2
